# Generated by Django 5.0.1 on 2024-01-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0002_restorepasswordrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restorepasswordrequest',
            name='password',
        ),
    ]
