# Generated by Django 5.0.4 on 2024-04-28 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0005_ambientalbooksharepointpath'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambientalbooksharepointpath',
            old_name='path',
            new_name='bool_name',
        ),
        migrations.AddField(
            model_name='ambientalbooksharepointpath',
            name='book_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambientalbooksharepointpath',
            name='category',
            field=models.CharField(choices=[('criticisms', 'CRITICAS'), ('air_and_noise', 'AIRE Y RUIDO'), ('water', 'AGUA'), ('waste', 'RESIDUOS'), ('recnat_and_risk', 'RECNAT Y RIESGO'), ('others', 'OTROS')], default='criticisms', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambientalbooksharepointpath',
            name='receipt_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserSharepointDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
