# Generated by Django 5.0.4 on 2024-05-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0006_rename_path_ambientalbooksharepointpath_bool_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambientalbooksharepointpath',
            old_name='bool_name',
            new_name='text_path',
        ),
    ]
