# Generated by Django 5.0.4 on 2024-05-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0007_rename_bool_name_ambientalbooksharepointpath_text_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambientalbooksharepointpath',
            name='text_path',
        ),
    ]
